export const initialState = [
  {
    id: 1,
    tag: 'IT',
    title: '공부방',
    channel: '노마드코더',
    link: 'https://youtu.be/Jz8Sx1XYb04',
    start_date: '2022-04-01 18시 50분',
    end_date: '2022-04-10 18시 30분',
    question: '이 강의를 선택하신 이유 2가지만 알고 싶습니다.',
    FCFS: true,
    user_id: 'user1',
    number_of_lectures: 1,
    number_of_persons: 2,
    is_full: false,
    comment:
      '안녕하세요!!! 같이 공부하실 분을 찾고 있습니다!!! 같이 열공해봐요@@@',
    image: 'https://i.ytimg.com/vi/Jz8Sx1XYb04/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 2,
    tag: '경제',
    title: '공부해보자',
    channel: '월급쟁이부자들TV',
    link: 'https://youtu.be/bv3FI_s9x0Q',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 'user1',
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: false,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/Z_bjXEDGQvM/original.jpg',
    room_state: '모집 완료',
  },
  {
    id: 3,
    tag: '역사',
    title: '공부방',
    channel: '침착맨',
    link: 'https://youtu.be/QIIZpxDZjsk/playlist?list=PLif_jr7pPZADzkIUTkp1MpzrjA_FvLy_9',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 'user1',
    number_of_lectures: 6,
    number_of_persons: 2,
    is_full: true,
    image: 'https://i.ytimg.com/vi/QIIZpxDZjsk/original.jpg',
    comment: '안녕하세요',
    room_state: '모집 중',
  },
  {
    id: 4,
    tag: '외국어',
    title: '공부방',
    channel: '오픽 노잼',
    link: 'https://youtu.be/yT99smeHg24',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/yT99smeHg24/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 5,
    tag: '외국어',
    title: '공부방',
    channel: '354 삼오사',
    link: 'https://youtu.be/qto2GHAAJb0',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 5,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/qto2GHAAJb0/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 6,
    tag: '외국어',
    title: '공부공부',
    channel: '필미필미 TV',
    link: 'https://youtu.be/0faCtv1ommU',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 6,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/0faCtv1ommU/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 7,
    tag: 'IT',
    title: '공부방',
    channel: '코딩애플',
    link: 'https://youtu.be/bv3FI_s9x0Q',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/xkpcNolC270/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 8,
    tag: 'IT',
    title: '공부방',
    channel: '조코딩',
    link: 'https://youtu.be/bv3FI_s9x0Q',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/4CWng2wWy9I/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 9,
    tag: '외국어',
    title: '공부방',
    channel: '파워게르만POGER',
    link: 'https://youtu.be/6C1zGgL0mN8',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/6C1zGgL0mN8/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 10,
    tag: '역사',
    title: '공부방',
    channel: '궁금소',
    link: 'https://youtu.be/0WrKixcBp3c',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/0WrKixcBp3c/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 11,
    tag: '역사',
    title: '공부방',
    channel: '쏨작가의 지식사전',
    link: 'https://youtu.be/52X9qhiNfok',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/52X9qhiNfok/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 12,
    tag: '외국어',
    title: '공부방',
    channel: '해커스 공식 유튜브',
    link: 'https://youtu.be/duY-zti6vn0',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/duY-zti6vn0/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 13,
    tag: '외국어',
    title: '공부방',
    channel: '사피엔스 스튜디오',
    link: 'https://youtu.be/Bg9fNm12eo8',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/Bg9fNm12eo8/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 14,
    tag: '역사',
    title: '공부방',
    channel: '쏨작가의 지식사전',
    link: 'https://youtu.be/KIzRt_jZbyw',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/KIzRt_jZbyw/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 15,
    tag: '역사',
    title: '공부방',
    channel: '별별역사',
    link: 'https://youtu.be/fNxtOypVUgA',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/fNxtOypVUgA/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 16,
    tag: 'IT',
    title: '공부방',
    channel: '드림코딩',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/By_qxt0SZlI/original.jpg',
    room_state: '모집 완료',
  },
  {
    id: 17,
    tag: 'IT',
    title: '공부방',
    channel: '코딩애플',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/v67LloZ1ieI/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 18,
    tag: 'IT',
    title: '공부방',
    channel: '코딩앙마',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/KF6t61yuPCY/original.jpg',
    room_state: '모집 완료',
  },
  {
    id: 19,
    tag: '역사',
    title: '공부방',
    channel: '당신이 몰랐던 이야기',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/n6yS7l-gsSU/original.jpg',
    room_state: '모집 완료',
  },
  {
    id: 20,
    tag: '경제',
    title: '공부방',
    channel: '한국경제TV',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/8u6HkKw-nLE/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 21,
    tag: '경제',
    title: '공부방',
    channel: '한국경제TV',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/2-NsZUb6vQg/original.jpg',
    room_state: '모집 중',
  },
];

export const initialState1 = [
  {
    id: 1,
    tag: 'IT',
    title: '공부방',
    channel: '노마드코더',
    link: 'https://youtu.be/Jz8Sx1XYb04',
    start_date: '2022-04-01 18시 50분',
    end_date: '2022-04-10 18시 30분',
    question: '이 강의를 선택하신 이유 2가지만 알고 싶습니다.',
    FCFS: true,
    user_id: 'user1',
    number_of_lectures: 1,
    number_of_persons: 2,
    is_full: false,
    comment:
      '안녕하세요!!! 같이 공부하실 분을 찾고 있습니다!!! 같이 열공해봐요@@@',
    image: 'https://i.ytimg.com/vi/Jz8Sx1XYb04/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 2,
    tag: '경제',
    title: '공부해보자',
    channel: '월급쟁이부자들TV',
    link: 'https://youtu.be/bv3FI_s9x0Q',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: '직장인이신가요?',
    FCFS: true,
    user_id: 'user1',
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: false,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/Z_bjXEDGQvM/original.jpg',
    room_state: '모집 완료',
    req_id: 'user2',
    mate_id: 'user2',
    mate_nickname: 'N잡러',
    mate_info: '좋아요 4개',
    mate_answer: '월급쟁이 평범한 30대 직장인입니다!',
  },
  {
    id: 3,
    tag: '역사',
    title: '공부방',
    channel: '침착맨',
    link: 'https://youtu.be/QIIZpxDZjsk/playlist?list=PLif_jr7pPZADzkIUTkp1MpzrjA_FvLy_9',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 'user1',
    number_of_lectures: 6,
    number_of_persons: 2,
    is_full: true,
    image: 'https://i.ytimg.com/vi/QIIZpxDZjsk/original.jpg',
    comment: '안녕하세요',
    room_state: '모집 중',
  },
  {
    id: 4,
    tag: '외국어',
    title: '공부방',
    channel: '오픽 노잼',
    link: 'https://youtu.be/yT99smeHg24',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/yT99smeHg24/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 5,
    tag: '외국어',
    title: '공부방',
    channel: '354 삼오사',
    link: 'https://youtu.be/qto2GHAAJb0',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 5,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/qto2GHAAJb0/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 6,
    tag: '외국어',
    title: '공부공부',
    channel: '필미필미 TV',
    link: 'https://youtu.be/0faCtv1ommU',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 6,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/0faCtv1ommU/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 7,
    tag: 'IT',
    title: '공부방',
    channel: '코딩애플',
    link: 'https://youtu.be/bv3FI_s9x0Q',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/xkpcNolC270/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 8,
    tag: 'IT',
    title: '공부방',
    channel: '조코딩',
    link: 'https://youtu.be/bv3FI_s9x0Q',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/4CWng2wWy9I/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 9,
    tag: '외국어',
    title: '공부방',
    channel: '파워게르만POGER',
    link: 'https://youtu.be/6C1zGgL0mN8',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/6C1zGgL0mN8/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 10,
    tag: '역사',
    title: '공부방',
    channel: '궁금소',
    link: 'https://youtu.be/0WrKixcBp3c',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/0WrKixcBp3c/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 11,
    tag: '역사',
    title: '공부방',
    channel: '쏨작가의 지식사전',
    link: 'https://youtu.be/52X9qhiNfok',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 8,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/52X9qhiNfok/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 12,
    tag: '외국어',
    title: '공부방',
    channel: '해커스 공식 유튜브',
    link: 'https://youtu.be/duY-zti6vn0',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/duY-zti6vn0/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 13,
    tag: '외국어',
    title: '공부방',
    channel: '사피엔스 스튜디오',
    link: 'https://youtu.be/Bg9fNm12eo8',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/Bg9fNm12eo8/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 14,
    tag: '역사',
    title: '공부방',
    channel: '쏨작가의 지식사전',
    link: 'https://youtu.be/KIzRt_jZbyw',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/KIzRt_jZbyw/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 15,
    tag: '역사',
    title: '공부방',
    channel: '별별역사',
    link: 'https://youtu.be/fNxtOypVUgA',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 4,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/fNxtOypVUgA/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 16,
    tag: 'IT',
    title: '공부방',
    channel: '드림코딩',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/By_qxt0SZlI/original.jpg',
    room_state: '모집 완료',
    req_id: 'user1',
    mate_id: 'user1',
    mate_nickname: '미래의웹개발마스터',
    mate_info: '좋아요 10개',
    mate_answer: '프론트엔드 목표로 자바스크립트 공부중',
  },
  {
    id: 17,
    tag: 'IT',
    title: '공부방',
    channel: '코딩애플',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/v67LloZ1ieI/original.jpg',
    room_state: '모집 중',
    req_id: 'user1',
    mate_id: 'user2',
    mate_nickname: '미래의웹개발마스터',
    mate_info: '좋아요 10개',
    mate_answer: '프론트엔드 목표로 자바스크립트 공부중',
  },
  {
    id: 18,
    tag: 'IT',
    title: '공부방',
    channel: '코딩앙마',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/KF6t61yuPCY/original.jpg',
    room_state: '모집 완료',
  },
  {
    id: 19,
    tag: '역사',
    title: '공부방',
    channel: '당신이 몰랐던 이야기',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/n6yS7l-gsSU/original.jpg',
    room_state: '모집 완료',
  },
  {
    id: 20,
    tag: '경제',
    title: '공부방',
    channel: '한국경제TV',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/inDNtBbrork/original.jpg',
    room_state: '모집 중',
  },
  {
    id: 21,
    tag: '경제',
    title: '공부방',
    channel: '한국경제TV',
    link: 'https://youtu.be/By_qxt0SZlI',
    start_date: '2021-04-01',
    end_date: '2021-04-10',
    question: 'ㅇㅇㅇ',
    FCFS: true,
    user_id: 7,
    number_of_lectures: 2,
    number_of_persons: 2,
    is_full: true,
    comment: '안녕하세요',
    image: 'https://i.ytimg.com/vi/2-NsZUb6vQg/original.jpg',
    room_state: '모집 중',
  },
];
